title = "AWS CI/CD Pipeline with CodeGuru & UnitTest"
googleAnalytics = "UA-56850614-10"
anguageCode = "ko-KR"
defaultContentLanguage = "en"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true
#metaDataFormat = "yaml"
#baseURL = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "Seyong Kang"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> AWS Homepage"
  url = "https://aws.amazon.com/"
  weight = 1000

[[menu.shortcuts]]
  name = "<i class='fas fa-blog'></i> AWS Blog"
  url = "https://aws.amazon.com/blogs/aws/"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='fab fa-facebook-square'></i> Facebook"
  url = "https://www.facebook.com/groups/awskrug/"
  weight = 1030

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github"
  url = "https://github.com/sykang169/codequality_workshop.git"
  weight = 1040

[Languages]
  [Languages.en]
    weight = 1
    languageName = "English"

  [Languages.ko]
    weight = 2
    languageName = "한국어"


[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://codequality.workshop.kr/"
